// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GoodsInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GoodsInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace X {
namespace Res {
class GoodsInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GoodsInfo>
     _instance;
} _GoodsInfo_default_instance_;
class GoodsInfo_ARRAYDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GoodsInfo_ARRAY>
     _instance;
} _GoodsInfo_ARRAY_default_instance_;

namespace protobuf_GoodsInfo_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GoodsInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GoodsInfo_ARRAY, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GoodsInfo_ARRAY, items_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(GoodsInfo)},
  { 5, -1, sizeof(GoodsInfo_ARRAY)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_GoodsInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_GoodsInfo_ARRAY_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "GoodsInfo.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _GoodsInfo_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_GoodsInfo_default_instance_);_GoodsInfo_ARRAY_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_GoodsInfo_ARRAY_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017GoodsInfo.proto\022\005X.Res\"\013\n\tGoodsInfo\"2\n"
      "\017GoodsInfo_ARRAY\022\037\n\005items\030\001 \003(\0132\020.X.Res."
      "GoodsInfob\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 97);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GoodsInfo.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_GoodsInfo_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GoodsInfo::GoodsInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_GoodsInfo_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:X.Res.GoodsInfo)
}
GoodsInfo::GoodsInfo(const GoodsInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:X.Res.GoodsInfo)
}

void GoodsInfo::SharedCtor() {
  _cached_size_ = 0;
}

GoodsInfo::~GoodsInfo() {
  // @@protoc_insertion_point(destructor:X.Res.GoodsInfo)
  SharedDtor();
}

void GoodsInfo::SharedDtor() {
}

void GoodsInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GoodsInfo::descriptor() {
  protobuf_GoodsInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GoodsInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GoodsInfo& GoodsInfo::default_instance() {
  protobuf_GoodsInfo_2eproto::InitDefaults();
  return *internal_default_instance();
}

GoodsInfo* GoodsInfo::New(::google::protobuf::Arena* arena) const {
  GoodsInfo* n = new GoodsInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GoodsInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:X.Res.GoodsInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool GoodsInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:X.Res.GoodsInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:X.Res.GoodsInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:X.Res.GoodsInfo)
  return false;
#undef DO_
}

void GoodsInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:X.Res.GoodsInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:X.Res.GoodsInfo)
}

::google::protobuf::uint8* GoodsInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:X.Res.GoodsInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:X.Res.GoodsInfo)
  return target;
}

size_t GoodsInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:X.Res.GoodsInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GoodsInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:X.Res.GoodsInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const GoodsInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GoodsInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:X.Res.GoodsInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:X.Res.GoodsInfo)
    MergeFrom(*source);
  }
}

void GoodsInfo::MergeFrom(const GoodsInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:X.Res.GoodsInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GoodsInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:X.Res.GoodsInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GoodsInfo::CopyFrom(const GoodsInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:X.Res.GoodsInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GoodsInfo::IsInitialized() const {
  return true;
}

void GoodsInfo::Swap(GoodsInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GoodsInfo::InternalSwap(GoodsInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GoodsInfo::GetMetadata() const {
  protobuf_GoodsInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GoodsInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GoodsInfo

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GoodsInfo_ARRAY::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GoodsInfo_ARRAY::GoodsInfo_ARRAY()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_GoodsInfo_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:X.Res.GoodsInfo_ARRAY)
}
GoodsInfo_ARRAY::GoodsInfo_ARRAY(const GoodsInfo_ARRAY& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      items_(from.items_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:X.Res.GoodsInfo_ARRAY)
}

void GoodsInfo_ARRAY::SharedCtor() {
  _cached_size_ = 0;
}

GoodsInfo_ARRAY::~GoodsInfo_ARRAY() {
  // @@protoc_insertion_point(destructor:X.Res.GoodsInfo_ARRAY)
  SharedDtor();
}

void GoodsInfo_ARRAY::SharedDtor() {
}

void GoodsInfo_ARRAY::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GoodsInfo_ARRAY::descriptor() {
  protobuf_GoodsInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GoodsInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GoodsInfo_ARRAY& GoodsInfo_ARRAY::default_instance() {
  protobuf_GoodsInfo_2eproto::InitDefaults();
  return *internal_default_instance();
}

GoodsInfo_ARRAY* GoodsInfo_ARRAY::New(::google::protobuf::Arena* arena) const {
  GoodsInfo_ARRAY* n = new GoodsInfo_ARRAY;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GoodsInfo_ARRAY::Clear() {
// @@protoc_insertion_point(message_clear_start:X.Res.GoodsInfo_ARRAY)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear();
}

bool GoodsInfo_ARRAY::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:X.Res.GoodsInfo_ARRAY)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .X.Res.GoodsInfo items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:X.Res.GoodsInfo_ARRAY)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:X.Res.GoodsInfo_ARRAY)
  return false;
#undef DO_
}

void GoodsInfo_ARRAY::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:X.Res.GoodsInfo_ARRAY)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .X.Res.GoodsInfo items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->items(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:X.Res.GoodsInfo_ARRAY)
}

::google::protobuf::uint8* GoodsInfo_ARRAY::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:X.Res.GoodsInfo_ARRAY)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .X.Res.GoodsInfo items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->items(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:X.Res.GoodsInfo_ARRAY)
  return target;
}

size_t GoodsInfo_ARRAY::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:X.Res.GoodsInfo_ARRAY)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .X.Res.GoodsInfo items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GoodsInfo_ARRAY::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:X.Res.GoodsInfo_ARRAY)
  GOOGLE_DCHECK_NE(&from, this);
  const GoodsInfo_ARRAY* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GoodsInfo_ARRAY>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:X.Res.GoodsInfo_ARRAY)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:X.Res.GoodsInfo_ARRAY)
    MergeFrom(*source);
  }
}

void GoodsInfo_ARRAY::MergeFrom(const GoodsInfo_ARRAY& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:X.Res.GoodsInfo_ARRAY)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void GoodsInfo_ARRAY::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:X.Res.GoodsInfo_ARRAY)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GoodsInfo_ARRAY::CopyFrom(const GoodsInfo_ARRAY& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:X.Res.GoodsInfo_ARRAY)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GoodsInfo_ARRAY::IsInitialized() const {
  return true;
}

void GoodsInfo_ARRAY::Swap(GoodsInfo_ARRAY* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GoodsInfo_ARRAY::InternalSwap(GoodsInfo_ARRAY* other) {
  using std::swap;
  items_.InternalSwap(&other->items_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GoodsInfo_ARRAY::GetMetadata() const {
  protobuf_GoodsInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GoodsInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GoodsInfo_ARRAY

// repeated .X.Res.GoodsInfo items = 1;
int GoodsInfo_ARRAY::items_size() const {
  return items_.size();
}
void GoodsInfo_ARRAY::clear_items() {
  items_.Clear();
}
const ::X::Res::GoodsInfo& GoodsInfo_ARRAY::items(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo_ARRAY.items)
  return items_.Get(index);
}
::X::Res::GoodsInfo* GoodsInfo_ARRAY::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo_ARRAY.items)
  return items_.Mutable(index);
}
::X::Res::GoodsInfo* GoodsInfo_ARRAY::add_items() {
  // @@protoc_insertion_point(field_add:X.Res.GoodsInfo_ARRAY.items)
  return items_.Add();
}
::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo >*
GoodsInfo_ARRAY::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GoodsInfo_ARRAY.items)
  return &items_;
}
const ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo >&
GoodsInfo_ARRAY::items() const {
  // @@protoc_insertion_point(field_list:X.Res.GoodsInfo_ARRAY.items)
  return items_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Res
}  // namespace X

// @@protoc_insertion_point(global_scope)
