// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GOODS_INFO.proto

#ifndef PROTOBUF_GOODS_5fINFO_2eproto__INCLUDED
#define PROTOBUF_GOODS_5fINFO_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace X {
namespace Res {
class GOODS_INFO;
class GOODS_INFODefaultTypeInternal;
extern GOODS_INFODefaultTypeInternal _GOODS_INFO_default_instance_;
class GOODS_INFO_ARRAY;
class GOODS_INFO_ARRAYDefaultTypeInternal;
extern GOODS_INFO_ARRAYDefaultTypeInternal _GOODS_INFO_ARRAY_default_instance_;
class GOODS_INFO_GoodsAttr;
class GOODS_INFO_GoodsAttrDefaultTypeInternal;
extern GOODS_INFO_GoodsAttrDefaultTypeInternal _GOODS_INFO_GoodsAttr_default_instance_;
class GOODS_INFO_Price;
class GOODS_INFO_PriceDefaultTypeInternal;
extern GOODS_INFO_PriceDefaultTypeInternal _GOODS_INFO_Price_default_instance_;
}  // namespace Res
}  // namespace X

namespace X {
namespace Res {

namespace protobuf_GOODS_5fINFO_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_GOODS_5fINFO_2eproto

// ===================================================================

class GOODS_INFO_Price : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.GOODS_INFO.Price) */ {
 public:
  GOODS_INFO_Price();
  virtual ~GOODS_INFO_Price();

  GOODS_INFO_Price(const GOODS_INFO_Price& from);

  inline GOODS_INFO_Price& operator=(const GOODS_INFO_Price& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GOODS_INFO_Price(GOODS_INFO_Price&& from) noexcept
    : GOODS_INFO_Price() {
    *this = ::std::move(from);
  }

  inline GOODS_INFO_Price& operator=(GOODS_INFO_Price&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GOODS_INFO_Price& default_instance();

  static inline const GOODS_INFO_Price* internal_default_instance() {
    return reinterpret_cast<const GOODS_INFO_Price*>(
               &_GOODS_INFO_Price_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GOODS_INFO_Price* other);
  friend void swap(GOODS_INFO_Price& a, GOODS_INFO_Price& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GOODS_INFO_Price* New() const PROTOBUF_FINAL { return New(NULL); }

  GOODS_INFO_Price* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GOODS_INFO_Price& from);
  void MergeFrom(const GOODS_INFO_Price& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GOODS_INFO_Price* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 price_dq = 1;
  void clear_price_dq();
  static const int kPriceDqFieldNumber = 1;
  ::google::protobuf::uint32 price_dq() const;
  void set_price_dq(::google::protobuf::uint32 value);

  // uint32 price_gold = 2;
  void clear_price_gold();
  static const int kPriceGoldFieldNumber = 2;
  ::google::protobuf::uint32 price_gold() const;
  void set_price_gold(::google::protobuf::uint32 value);

  // uint32 price_value = 3;
  void clear_price_value();
  static const int kPriceValueFieldNumber = 3;
  ::google::protobuf::uint32 price_value() const;
  void set_price_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:X.Res.GOODS_INFO.Price)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 price_dq_;
  ::google::protobuf::uint32 price_gold_;
  ::google::protobuf::uint32 price_value_;
  mutable int _cached_size_;
  friend struct protobuf_GOODS_5fINFO_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GOODS_INFO_GoodsAttr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.GOODS_INFO.GoodsAttr) */ {
 public:
  GOODS_INFO_GoodsAttr();
  virtual ~GOODS_INFO_GoodsAttr();

  GOODS_INFO_GoodsAttr(const GOODS_INFO_GoodsAttr& from);

  inline GOODS_INFO_GoodsAttr& operator=(const GOODS_INFO_GoodsAttr& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GOODS_INFO_GoodsAttr(GOODS_INFO_GoodsAttr&& from) noexcept
    : GOODS_INFO_GoodsAttr() {
    *this = ::std::move(from);
  }

  inline GOODS_INFO_GoodsAttr& operator=(GOODS_INFO_GoodsAttr&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GOODS_INFO_GoodsAttr& default_instance();

  static inline const GOODS_INFO_GoodsAttr* internal_default_instance() {
    return reinterpret_cast<const GOODS_INFO_GoodsAttr*>(
               &_GOODS_INFO_GoodsAttr_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(GOODS_INFO_GoodsAttr* other);
  friend void swap(GOODS_INFO_GoodsAttr& a, GOODS_INFO_GoodsAttr& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GOODS_INFO_GoodsAttr* New() const PROTOBUF_FINAL { return New(NULL); }

  GOODS_INFO_GoodsAttr* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GOODS_INFO_GoodsAttr& from);
  void MergeFrom(const GOODS_INFO_GoodsAttr& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GOODS_INFO_GoodsAttr* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 attr_type = 1;
  void clear_attr_type();
  static const int kAttrTypeFieldNumber = 1;
  ::google::protobuf::uint32 attr_type() const;
  void set_attr_type(::google::protobuf::uint32 value);

  // uint32 attr_value = 2;
  void clear_attr_value();
  static const int kAttrValueFieldNumber = 2;
  ::google::protobuf::uint32 attr_value() const;
  void set_attr_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:X.Res.GOODS_INFO.GoodsAttr)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 attr_type_;
  ::google::protobuf::uint32 attr_value_;
  mutable int _cached_size_;
  friend struct protobuf_GOODS_5fINFO_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GOODS_INFO : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.GOODS_INFO) */ {
 public:
  GOODS_INFO();
  virtual ~GOODS_INFO();

  GOODS_INFO(const GOODS_INFO& from);

  inline GOODS_INFO& operator=(const GOODS_INFO& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GOODS_INFO(GOODS_INFO&& from) noexcept
    : GOODS_INFO() {
    *this = ::std::move(from);
  }

  inline GOODS_INFO& operator=(GOODS_INFO&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GOODS_INFO& default_instance();

  static inline const GOODS_INFO* internal_default_instance() {
    return reinterpret_cast<const GOODS_INFO*>(
               &_GOODS_INFO_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GOODS_INFO* other);
  friend void swap(GOODS_INFO& a, GOODS_INFO& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GOODS_INFO* New() const PROTOBUF_FINAL { return New(NULL); }

  GOODS_INFO* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GOODS_INFO& from);
  void MergeFrom(const GOODS_INFO& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GOODS_INFO* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GOODS_INFO_Price Price;
  typedef GOODS_INFO_GoodsAttr GoodsAttr;

  // accessors -------------------------------------------------------

  // repeated uint32 privileged_plat_id_list = 14;
  int privileged_plat_id_list_size() const;
  void clear_privileged_plat_id_list();
  static const int kPrivilegedPlatIdListFieldNumber = 14;
  ::google::protobuf::uint32 privileged_plat_id_list(int index) const;
  void set_privileged_plat_id_list(int index, ::google::protobuf::uint32 value);
  void add_privileged_plat_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      privileged_plat_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_privileged_plat_id_list();

  // repeated .X.Res.GOODS_INFO.Price price_table = 27;
  int price_table_size() const;
  void clear_price_table();
  static const int kPriceTableFieldNumber = 27;
  const ::X::Res::GOODS_INFO_Price& price_table(int index) const;
  ::X::Res::GOODS_INFO_Price* mutable_price_table(int index);
  ::X::Res::GOODS_INFO_Price* add_price_table();
  ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_Price >*
      mutable_price_table();
  const ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_Price >&
      price_table() const;

  // repeated .X.Res.GOODS_INFO.GoodsAttr goods_attr = 28;
  int goods_attr_size() const;
  void clear_goods_attr();
  static const int kGoodsAttrFieldNumber = 28;
  const ::X::Res::GOODS_INFO_GoodsAttr& goods_attr(int index) const;
  ::X::Res::GOODS_INFO_GoodsAttr* mutable_goods_attr(int index);
  ::X::Res::GOODS_INFO_GoodsAttr* add_goods_attr();
  ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_GoodsAttr >*
      mutable_goods_attr();
  const ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_GoodsAttr >&
      goods_attr() const;

  // bytes name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // bytes online_time = 12;
  void clear_online_time();
  static const int kOnlineTimeFieldNumber = 12;
  const ::std::string& online_time() const;
  void set_online_time(const ::std::string& value);
  #if LANG_CXX11
  void set_online_time(::std::string&& value);
  #endif
  void set_online_time(const char* value);
  void set_online_time(const void* value, size_t size);
  ::std::string* mutable_online_time();
  ::std::string* release_online_time();
  void set_allocated_online_time(::std::string* online_time);

  // bytes offline_time = 13;
  void clear_offline_time();
  static const int kOfflineTimeFieldNumber = 13;
  const ::std::string& offline_time() const;
  void set_offline_time(const ::std::string& value);
  #if LANG_CXX11
  void set_offline_time(::std::string&& value);
  #endif
  void set_offline_time(const char* value);
  void set_offline_time(const void* value, size_t size);
  ::std::string* mutable_offline_time();
  ::std::string* release_offline_time();
  void set_allocated_offline_time(::std::string* offline_time);

  // bytes valid_time = 19;
  void clear_valid_time();
  static const int kValidTimeFieldNumber = 19;
  const ::std::string& valid_time() const;
  void set_valid_time(const ::std::string& value);
  #if LANG_CXX11
  void set_valid_time(::std::string&& value);
  #endif
  void set_valid_time(const char* value);
  void set_valid_time(const void* value, size_t size);
  ::std::string* mutable_valid_time();
  ::std::string* release_valid_time();
  void set_allocated_valid_time(::std::string* valid_time);

  // bytes status = 23;
  void clear_status();
  static const int kStatusFieldNumber = 23;
  const ::std::string& status() const;
  void set_status(const ::std::string& value);
  #if LANG_CXX11
  void set_status(::std::string&& value);
  #endif
  void set_status(const char* value);
  void set_status(const void* value, size_t size);
  ::std::string* mutable_status();
  ::std::string* release_status();
  void set_allocated_status(::std::string* status);

  // bytes description = 29;
  void clear_description();
  static const int kDescriptionFieldNumber = 29;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const void* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // bytes subSystemId = 31;
  void clear_subsystemid();
  static const int kSubSystemIdFieldNumber = 31;
  const ::std::string& subsystemid() const;
  void set_subsystemid(const ::std::string& value);
  #if LANG_CXX11
  void set_subsystemid(::std::string&& value);
  #endif
  void set_subsystemid(const char* value);
  void set_subsystemid(const void* value, size_t size);
  ::std::string* mutable_subsystemid();
  ::std::string* release_subsystemid();
  void set_allocated_subsystemid(::std::string* subsystemid);

  // uint32 goods_id = 1;
  void clear_goods_id();
  static const int kGoodsIdFieldNumber = 1;
  ::google::protobuf::uint32 goods_id() const;
  void set_goods_id(::google::protobuf::uint32 value);

  // uint32 sex = 3;
  void clear_sex();
  static const int kSexFieldNumber = 3;
  ::google::protobuf::uint32 sex() const;
  void set_sex(::google::protobuf::uint32 value);

  // uint32 level_limit = 4;
  void clear_level_limit();
  static const int kLevelLimitFieldNumber = 4;
  ::google::protobuf::uint32 level_limit() const;
  void set_level_limit(::google::protobuf::uint32 value);

  // int32 club_vip_level = 5;
  void clear_club_vip_level();
  static const int kClubVipLevelFieldNumber = 5;
  ::google::protobuf::int32 club_vip_level() const;
  void set_club_vip_level(::google::protobuf::int32 value);

  // int32 qb_2 = 6;
  void clear_qb_2();
  static const int kQb2FieldNumber = 6;
  ::google::protobuf::int32 qb_2() const;
  void set_qb_2(::google::protobuf::int32 value);

  // uint32 consume_type = 7;
  void clear_consume_type();
  static const int kConsumeTypeFieldNumber = 7;
  ::google::protobuf::uint32 consume_type() const;
  void set_consume_type(::google::protobuf::uint32 value);

  // uint32 time_unit = 8;
  void clear_time_unit();
  static const int kTimeUnitFieldNumber = 8;
  ::google::protobuf::uint32 time_unit() const;
  void set_time_unit(::google::protobuf::uint32 value);

  // uint32 is_online = 9;
  void clear_is_online();
  static const int kIsOnlineFieldNumber = 9;
  ::google::protobuf::uint32 is_online() const;
  void set_is_online(::google::protobuf::uint32 value);

  // uint32 can_buy = 10;
  void clear_can_buy();
  static const int kCanBuyFieldNumber = 10;
  ::google::protobuf::uint32 can_buy() const;
  void set_can_buy(::google::protobuf::uint32 value);

  // uint32 can_recharge = 11;
  void clear_can_recharge();
  static const int kCanRechargeFieldNumber = 11;
  ::google::protobuf::uint32 can_recharge() const;
  void set_can_recharge(::google::protobuf::uint32 value);

  // uint32 privileged_plat_is_online = 15;
  void clear_privileged_plat_is_online();
  static const int kPrivilegedPlatIsOnlineFieldNumber = 15;
  ::google::protobuf::uint32 privileged_plat_is_online() const;
  void set_privileged_plat_is_online(::google::protobuf::uint32 value);

  // uint32 privileged_plat_can_buy = 16;
  void clear_privileged_plat_can_buy();
  static const int kPrivilegedPlatCanBuyFieldNumber = 16;
  ::google::protobuf::uint32 privileged_plat_can_buy() const;
  void set_privileged_plat_can_buy(::google::protobuf::uint32 value);

  // uint32 privileged_plat_can_recharge = 17;
  void clear_privileged_plat_can_recharge();
  static const int kPrivilegedPlatCanRechargeFieldNumber = 17;
  ::google::protobuf::uint32 privileged_plat_can_recharge() const;
  void set_privileged_plat_can_recharge(::google::protobuf::uint32 value);

  // uint32 payment_terms = 18;
  void clear_payment_terms();
  static const int kPaymentTermsFieldNumber = 18;
  ::google::protobuf::uint32 payment_terms() const;
  void set_payment_terms(::google::protobuf::uint32 value);

  // uint32 sort_priority = 20;
  void clear_sort_priority();
  static const int kSortPriorityFieldNumber = 20;
  ::google::protobuf::uint32 sort_priority() const;
  void set_sort_priority(::google::protobuf::uint32 value);

  // int32 suit_number = 21;
  void clear_suit_number();
  static const int kSuitNumberFieldNumber = 21;
  ::google::protobuf::int32 suit_number() const;
  void set_suit_number(::google::protobuf::int32 value);

  // uint32 bag_sort_priority = 22;
  void clear_bag_sort_priority();
  static const int kBagSortPriorityFieldNumber = 22;
  ::google::protobuf::uint32 bag_sort_priority() const;
  void set_bag_sort_priority(::google::protobuf::uint32 value);

  // uint32 rank = 24;
  void clear_rank();
  static const int kRankFieldNumber = 24;
  ::google::protobuf::uint32 rank() const;
  void set_rank(::google::protobuf::uint32 value);

  // uint32 price_discount = 25;
  void clear_price_discount();
  static const int kPriceDiscountFieldNumber = 25;
  ::google::protobuf::uint32 price_discount() const;
  void set_price_discount(::google::protobuf::uint32 value);

  // uint32 vip_discount = 26;
  void clear_vip_discount();
  static const int kVipDiscountFieldNumber = 26;
  ::google::protobuf::uint32 vip_discount() const;
  void set_vip_discount(::google::protobuf::uint32 value);

  // uint32 limit_id = 30;
  void clear_limit_id();
  static const int kLimitIdFieldNumber = 30;
  ::google::protobuf::uint32 limit_id() const;
  void set_limit_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:X.Res.GOODS_INFO)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > privileged_plat_id_list_;
  mutable int _privileged_plat_id_list_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_Price > price_table_;
  ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_GoodsAttr > goods_attr_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr online_time_;
  ::google::protobuf::internal::ArenaStringPtr offline_time_;
  ::google::protobuf::internal::ArenaStringPtr valid_time_;
  ::google::protobuf::internal::ArenaStringPtr status_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr subsystemid_;
  ::google::protobuf::uint32 goods_id_;
  ::google::protobuf::uint32 sex_;
  ::google::protobuf::uint32 level_limit_;
  ::google::protobuf::int32 club_vip_level_;
  ::google::protobuf::int32 qb_2_;
  ::google::protobuf::uint32 consume_type_;
  ::google::protobuf::uint32 time_unit_;
  ::google::protobuf::uint32 is_online_;
  ::google::protobuf::uint32 can_buy_;
  ::google::protobuf::uint32 can_recharge_;
  ::google::protobuf::uint32 privileged_plat_is_online_;
  ::google::protobuf::uint32 privileged_plat_can_buy_;
  ::google::protobuf::uint32 privileged_plat_can_recharge_;
  ::google::protobuf::uint32 payment_terms_;
  ::google::protobuf::uint32 sort_priority_;
  ::google::protobuf::int32 suit_number_;
  ::google::protobuf::uint32 bag_sort_priority_;
  ::google::protobuf::uint32 rank_;
  ::google::protobuf::uint32 price_discount_;
  ::google::protobuf::uint32 vip_discount_;
  ::google::protobuf::uint32 limit_id_;
  mutable int _cached_size_;
  friend struct protobuf_GOODS_5fINFO_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GOODS_INFO_ARRAY : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.GOODS_INFO_ARRAY) */ {
 public:
  GOODS_INFO_ARRAY();
  virtual ~GOODS_INFO_ARRAY();

  GOODS_INFO_ARRAY(const GOODS_INFO_ARRAY& from);

  inline GOODS_INFO_ARRAY& operator=(const GOODS_INFO_ARRAY& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GOODS_INFO_ARRAY(GOODS_INFO_ARRAY&& from) noexcept
    : GOODS_INFO_ARRAY() {
    *this = ::std::move(from);
  }

  inline GOODS_INFO_ARRAY& operator=(GOODS_INFO_ARRAY&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GOODS_INFO_ARRAY& default_instance();

  static inline const GOODS_INFO_ARRAY* internal_default_instance() {
    return reinterpret_cast<const GOODS_INFO_ARRAY*>(
               &_GOODS_INFO_ARRAY_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GOODS_INFO_ARRAY* other);
  friend void swap(GOODS_INFO_ARRAY& a, GOODS_INFO_ARRAY& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GOODS_INFO_ARRAY* New() const PROTOBUF_FINAL { return New(NULL); }

  GOODS_INFO_ARRAY* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GOODS_INFO_ARRAY& from);
  void MergeFrom(const GOODS_INFO_ARRAY& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GOODS_INFO_ARRAY* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .X.Res.GOODS_INFO items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::X::Res::GOODS_INFO& items(int index) const;
  ::X::Res::GOODS_INFO* mutable_items(int index);
  ::X::Res::GOODS_INFO* add_items();
  ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO >&
      items() const;

  // @@protoc_insertion_point(class_scope:X.Res.GOODS_INFO_ARRAY)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO > items_;
  mutable int _cached_size_;
  friend struct protobuf_GOODS_5fINFO_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GOODS_INFO_Price

// uint32 price_dq = 1;
inline void GOODS_INFO_Price::clear_price_dq() {
  price_dq_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO_Price::price_dq() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.Price.price_dq)
  return price_dq_;
}
inline void GOODS_INFO_Price::set_price_dq(::google::protobuf::uint32 value) {
  
  price_dq_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.Price.price_dq)
}

// uint32 price_gold = 2;
inline void GOODS_INFO_Price::clear_price_gold() {
  price_gold_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO_Price::price_gold() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.Price.price_gold)
  return price_gold_;
}
inline void GOODS_INFO_Price::set_price_gold(::google::protobuf::uint32 value) {
  
  price_gold_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.Price.price_gold)
}

// uint32 price_value = 3;
inline void GOODS_INFO_Price::clear_price_value() {
  price_value_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO_Price::price_value() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.Price.price_value)
  return price_value_;
}
inline void GOODS_INFO_Price::set_price_value(::google::protobuf::uint32 value) {
  
  price_value_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.Price.price_value)
}

// -------------------------------------------------------------------

// GOODS_INFO_GoodsAttr

// uint32 attr_type = 1;
inline void GOODS_INFO_GoodsAttr::clear_attr_type() {
  attr_type_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO_GoodsAttr::attr_type() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.GoodsAttr.attr_type)
  return attr_type_;
}
inline void GOODS_INFO_GoodsAttr::set_attr_type(::google::protobuf::uint32 value) {
  
  attr_type_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.GoodsAttr.attr_type)
}

// uint32 attr_value = 2;
inline void GOODS_INFO_GoodsAttr::clear_attr_value() {
  attr_value_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO_GoodsAttr::attr_value() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.GoodsAttr.attr_value)
  return attr_value_;
}
inline void GOODS_INFO_GoodsAttr::set_attr_value(::google::protobuf::uint32 value) {
  
  attr_value_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.GoodsAttr.attr_value)
}

// -------------------------------------------------------------------

// GOODS_INFO

// uint32 goods_id = 1;
inline void GOODS_INFO::clear_goods_id() {
  goods_id_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::goods_id() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.goods_id)
  return goods_id_;
}
inline void GOODS_INFO::set_goods_id(::google::protobuf::uint32 value) {
  
  goods_id_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.goods_id)
}

// bytes name = 2;
inline void GOODS_INFO::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GOODS_INFO::name() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.name)
  return name_.GetNoArena();
}
inline void GOODS_INFO::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.name)
}
#if LANG_CXX11
inline void GOODS_INFO::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GOODS_INFO.name)
}
#endif
inline void GOODS_INFO::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GOODS_INFO.name)
}
inline void GOODS_INFO::set_name(const void* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GOODS_INFO.name)
}
inline ::std::string* GOODS_INFO::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GOODS_INFO::release_name() {
  // @@protoc_insertion_point(field_release:X.Res.GOODS_INFO.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GOODS_INFO::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GOODS_INFO.name)
}

// uint32 sex = 3;
inline void GOODS_INFO::clear_sex() {
  sex_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::sex() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.sex)
  return sex_;
}
inline void GOODS_INFO::set_sex(::google::protobuf::uint32 value) {
  
  sex_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.sex)
}

// uint32 level_limit = 4;
inline void GOODS_INFO::clear_level_limit() {
  level_limit_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::level_limit() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.level_limit)
  return level_limit_;
}
inline void GOODS_INFO::set_level_limit(::google::protobuf::uint32 value) {
  
  level_limit_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.level_limit)
}

// int32 club_vip_level = 5;
inline void GOODS_INFO::clear_club_vip_level() {
  club_vip_level_ = 0;
}
inline ::google::protobuf::int32 GOODS_INFO::club_vip_level() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.club_vip_level)
  return club_vip_level_;
}
inline void GOODS_INFO::set_club_vip_level(::google::protobuf::int32 value) {
  
  club_vip_level_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.club_vip_level)
}

// int32 qb_2 = 6;
inline void GOODS_INFO::clear_qb_2() {
  qb_2_ = 0;
}
inline ::google::protobuf::int32 GOODS_INFO::qb_2() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.qb_2)
  return qb_2_;
}
inline void GOODS_INFO::set_qb_2(::google::protobuf::int32 value) {
  
  qb_2_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.qb_2)
}

// uint32 consume_type = 7;
inline void GOODS_INFO::clear_consume_type() {
  consume_type_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::consume_type() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.consume_type)
  return consume_type_;
}
inline void GOODS_INFO::set_consume_type(::google::protobuf::uint32 value) {
  
  consume_type_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.consume_type)
}

// uint32 time_unit = 8;
inline void GOODS_INFO::clear_time_unit() {
  time_unit_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::time_unit() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.time_unit)
  return time_unit_;
}
inline void GOODS_INFO::set_time_unit(::google::protobuf::uint32 value) {
  
  time_unit_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.time_unit)
}

// uint32 is_online = 9;
inline void GOODS_INFO::clear_is_online() {
  is_online_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::is_online() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.is_online)
  return is_online_;
}
inline void GOODS_INFO::set_is_online(::google::protobuf::uint32 value) {
  
  is_online_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.is_online)
}

// uint32 can_buy = 10;
inline void GOODS_INFO::clear_can_buy() {
  can_buy_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::can_buy() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.can_buy)
  return can_buy_;
}
inline void GOODS_INFO::set_can_buy(::google::protobuf::uint32 value) {
  
  can_buy_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.can_buy)
}

// uint32 can_recharge = 11;
inline void GOODS_INFO::clear_can_recharge() {
  can_recharge_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::can_recharge() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.can_recharge)
  return can_recharge_;
}
inline void GOODS_INFO::set_can_recharge(::google::protobuf::uint32 value) {
  
  can_recharge_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.can_recharge)
}

// bytes online_time = 12;
inline void GOODS_INFO::clear_online_time() {
  online_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GOODS_INFO::online_time() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.online_time)
  return online_time_.GetNoArena();
}
inline void GOODS_INFO::set_online_time(const ::std::string& value) {
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.online_time)
}
#if LANG_CXX11
inline void GOODS_INFO::set_online_time(::std::string&& value) {
  
  online_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GOODS_INFO.online_time)
}
#endif
inline void GOODS_INFO::set_online_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GOODS_INFO.online_time)
}
inline void GOODS_INFO::set_online_time(const void* value, size_t size) {
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GOODS_INFO.online_time)
}
inline ::std::string* GOODS_INFO::mutable_online_time() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.online_time)
  return online_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GOODS_INFO::release_online_time() {
  // @@protoc_insertion_point(field_release:X.Res.GOODS_INFO.online_time)
  
  return online_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GOODS_INFO::set_allocated_online_time(::std::string* online_time) {
  if (online_time != NULL) {
    
  } else {
    
  }
  online_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), online_time);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GOODS_INFO.online_time)
}

// bytes offline_time = 13;
inline void GOODS_INFO::clear_offline_time() {
  offline_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GOODS_INFO::offline_time() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.offline_time)
  return offline_time_.GetNoArena();
}
inline void GOODS_INFO::set_offline_time(const ::std::string& value) {
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.offline_time)
}
#if LANG_CXX11
inline void GOODS_INFO::set_offline_time(::std::string&& value) {
  
  offline_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GOODS_INFO.offline_time)
}
#endif
inline void GOODS_INFO::set_offline_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GOODS_INFO.offline_time)
}
inline void GOODS_INFO::set_offline_time(const void* value, size_t size) {
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GOODS_INFO.offline_time)
}
inline ::std::string* GOODS_INFO::mutable_offline_time() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.offline_time)
  return offline_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GOODS_INFO::release_offline_time() {
  // @@protoc_insertion_point(field_release:X.Res.GOODS_INFO.offline_time)
  
  return offline_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GOODS_INFO::set_allocated_offline_time(::std::string* offline_time) {
  if (offline_time != NULL) {
    
  } else {
    
  }
  offline_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), offline_time);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GOODS_INFO.offline_time)
}

// repeated uint32 privileged_plat_id_list = 14;
inline int GOODS_INFO::privileged_plat_id_list_size() const {
  return privileged_plat_id_list_.size();
}
inline void GOODS_INFO::clear_privileged_plat_id_list() {
  privileged_plat_id_list_.Clear();
}
inline ::google::protobuf::uint32 GOODS_INFO::privileged_plat_id_list(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.privileged_plat_id_list)
  return privileged_plat_id_list_.Get(index);
}
inline void GOODS_INFO::set_privileged_plat_id_list(int index, ::google::protobuf::uint32 value) {
  privileged_plat_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.privileged_plat_id_list)
}
inline void GOODS_INFO::add_privileged_plat_id_list(::google::protobuf::uint32 value) {
  privileged_plat_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:X.Res.GOODS_INFO.privileged_plat_id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GOODS_INFO::privileged_plat_id_list() const {
  // @@protoc_insertion_point(field_list:X.Res.GOODS_INFO.privileged_plat_id_list)
  return privileged_plat_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GOODS_INFO::mutable_privileged_plat_id_list() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GOODS_INFO.privileged_plat_id_list)
  return &privileged_plat_id_list_;
}

// uint32 privileged_plat_is_online = 15;
inline void GOODS_INFO::clear_privileged_plat_is_online() {
  privileged_plat_is_online_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::privileged_plat_is_online() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.privileged_plat_is_online)
  return privileged_plat_is_online_;
}
inline void GOODS_INFO::set_privileged_plat_is_online(::google::protobuf::uint32 value) {
  
  privileged_plat_is_online_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.privileged_plat_is_online)
}

// uint32 privileged_plat_can_buy = 16;
inline void GOODS_INFO::clear_privileged_plat_can_buy() {
  privileged_plat_can_buy_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::privileged_plat_can_buy() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.privileged_plat_can_buy)
  return privileged_plat_can_buy_;
}
inline void GOODS_INFO::set_privileged_plat_can_buy(::google::protobuf::uint32 value) {
  
  privileged_plat_can_buy_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.privileged_plat_can_buy)
}

// uint32 privileged_plat_can_recharge = 17;
inline void GOODS_INFO::clear_privileged_plat_can_recharge() {
  privileged_plat_can_recharge_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::privileged_plat_can_recharge() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.privileged_plat_can_recharge)
  return privileged_plat_can_recharge_;
}
inline void GOODS_INFO::set_privileged_plat_can_recharge(::google::protobuf::uint32 value) {
  
  privileged_plat_can_recharge_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.privileged_plat_can_recharge)
}

// uint32 payment_terms = 18;
inline void GOODS_INFO::clear_payment_terms() {
  payment_terms_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::payment_terms() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.payment_terms)
  return payment_terms_;
}
inline void GOODS_INFO::set_payment_terms(::google::protobuf::uint32 value) {
  
  payment_terms_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.payment_terms)
}

// bytes valid_time = 19;
inline void GOODS_INFO::clear_valid_time() {
  valid_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GOODS_INFO::valid_time() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.valid_time)
  return valid_time_.GetNoArena();
}
inline void GOODS_INFO::set_valid_time(const ::std::string& value) {
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.valid_time)
}
#if LANG_CXX11
inline void GOODS_INFO::set_valid_time(::std::string&& value) {
  
  valid_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GOODS_INFO.valid_time)
}
#endif
inline void GOODS_INFO::set_valid_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GOODS_INFO.valid_time)
}
inline void GOODS_INFO::set_valid_time(const void* value, size_t size) {
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GOODS_INFO.valid_time)
}
inline ::std::string* GOODS_INFO::mutable_valid_time() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.valid_time)
  return valid_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GOODS_INFO::release_valid_time() {
  // @@protoc_insertion_point(field_release:X.Res.GOODS_INFO.valid_time)
  
  return valid_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GOODS_INFO::set_allocated_valid_time(::std::string* valid_time) {
  if (valid_time != NULL) {
    
  } else {
    
  }
  valid_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valid_time);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GOODS_INFO.valid_time)
}

// uint32 sort_priority = 20;
inline void GOODS_INFO::clear_sort_priority() {
  sort_priority_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::sort_priority() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.sort_priority)
  return sort_priority_;
}
inline void GOODS_INFO::set_sort_priority(::google::protobuf::uint32 value) {
  
  sort_priority_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.sort_priority)
}

// int32 suit_number = 21;
inline void GOODS_INFO::clear_suit_number() {
  suit_number_ = 0;
}
inline ::google::protobuf::int32 GOODS_INFO::suit_number() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.suit_number)
  return suit_number_;
}
inline void GOODS_INFO::set_suit_number(::google::protobuf::int32 value) {
  
  suit_number_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.suit_number)
}

// uint32 bag_sort_priority = 22;
inline void GOODS_INFO::clear_bag_sort_priority() {
  bag_sort_priority_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::bag_sort_priority() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.bag_sort_priority)
  return bag_sort_priority_;
}
inline void GOODS_INFO::set_bag_sort_priority(::google::protobuf::uint32 value) {
  
  bag_sort_priority_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.bag_sort_priority)
}

// bytes status = 23;
inline void GOODS_INFO::clear_status() {
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GOODS_INFO::status() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.status)
  return status_.GetNoArena();
}
inline void GOODS_INFO::set_status(const ::std::string& value) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.status)
}
#if LANG_CXX11
inline void GOODS_INFO::set_status(::std::string&& value) {
  
  status_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GOODS_INFO.status)
}
#endif
inline void GOODS_INFO::set_status(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GOODS_INFO.status)
}
inline void GOODS_INFO::set_status(const void* value, size_t size) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GOODS_INFO.status)
}
inline ::std::string* GOODS_INFO::mutable_status() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.status)
  return status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GOODS_INFO::release_status() {
  // @@protoc_insertion_point(field_release:X.Res.GOODS_INFO.status)
  
  return status_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GOODS_INFO::set_allocated_status(::std::string* status) {
  if (status != NULL) {
    
  } else {
    
  }
  status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GOODS_INFO.status)
}

// uint32 rank = 24;
inline void GOODS_INFO::clear_rank() {
  rank_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::rank() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.rank)
  return rank_;
}
inline void GOODS_INFO::set_rank(::google::protobuf::uint32 value) {
  
  rank_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.rank)
}

// uint32 price_discount = 25;
inline void GOODS_INFO::clear_price_discount() {
  price_discount_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::price_discount() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.price_discount)
  return price_discount_;
}
inline void GOODS_INFO::set_price_discount(::google::protobuf::uint32 value) {
  
  price_discount_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.price_discount)
}

// uint32 vip_discount = 26;
inline void GOODS_INFO::clear_vip_discount() {
  vip_discount_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::vip_discount() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.vip_discount)
  return vip_discount_;
}
inline void GOODS_INFO::set_vip_discount(::google::protobuf::uint32 value) {
  
  vip_discount_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.vip_discount)
}

// repeated .X.Res.GOODS_INFO.Price price_table = 27;
inline int GOODS_INFO::price_table_size() const {
  return price_table_.size();
}
inline void GOODS_INFO::clear_price_table() {
  price_table_.Clear();
}
inline const ::X::Res::GOODS_INFO_Price& GOODS_INFO::price_table(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.price_table)
  return price_table_.Get(index);
}
inline ::X::Res::GOODS_INFO_Price* GOODS_INFO::mutable_price_table(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.price_table)
  return price_table_.Mutable(index);
}
inline ::X::Res::GOODS_INFO_Price* GOODS_INFO::add_price_table() {
  // @@protoc_insertion_point(field_add:X.Res.GOODS_INFO.price_table)
  return price_table_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_Price >*
GOODS_INFO::mutable_price_table() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GOODS_INFO.price_table)
  return &price_table_;
}
inline const ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_Price >&
GOODS_INFO::price_table() const {
  // @@protoc_insertion_point(field_list:X.Res.GOODS_INFO.price_table)
  return price_table_;
}

// repeated .X.Res.GOODS_INFO.GoodsAttr goods_attr = 28;
inline int GOODS_INFO::goods_attr_size() const {
  return goods_attr_.size();
}
inline void GOODS_INFO::clear_goods_attr() {
  goods_attr_.Clear();
}
inline const ::X::Res::GOODS_INFO_GoodsAttr& GOODS_INFO::goods_attr(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.goods_attr)
  return goods_attr_.Get(index);
}
inline ::X::Res::GOODS_INFO_GoodsAttr* GOODS_INFO::mutable_goods_attr(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.goods_attr)
  return goods_attr_.Mutable(index);
}
inline ::X::Res::GOODS_INFO_GoodsAttr* GOODS_INFO::add_goods_attr() {
  // @@protoc_insertion_point(field_add:X.Res.GOODS_INFO.goods_attr)
  return goods_attr_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_GoodsAttr >*
GOODS_INFO::mutable_goods_attr() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GOODS_INFO.goods_attr)
  return &goods_attr_;
}
inline const ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO_GoodsAttr >&
GOODS_INFO::goods_attr() const {
  // @@protoc_insertion_point(field_list:X.Res.GOODS_INFO.goods_attr)
  return goods_attr_;
}

// bytes description = 29;
inline void GOODS_INFO::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GOODS_INFO::description() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.description)
  return description_.GetNoArena();
}
inline void GOODS_INFO::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.description)
}
#if LANG_CXX11
inline void GOODS_INFO::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GOODS_INFO.description)
}
#endif
inline void GOODS_INFO::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GOODS_INFO.description)
}
inline void GOODS_INFO::set_description(const void* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GOODS_INFO.description)
}
inline ::std::string* GOODS_INFO::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GOODS_INFO::release_description() {
  // @@protoc_insertion_point(field_release:X.Res.GOODS_INFO.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GOODS_INFO::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GOODS_INFO.description)
}

// uint32 limit_id = 30;
inline void GOODS_INFO::clear_limit_id() {
  limit_id_ = 0u;
}
inline ::google::protobuf::uint32 GOODS_INFO::limit_id() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.limit_id)
  return limit_id_;
}
inline void GOODS_INFO::set_limit_id(::google::protobuf::uint32 value) {
  
  limit_id_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.limit_id)
}

// bytes subSystemId = 31;
inline void GOODS_INFO::clear_subsystemid() {
  subsystemid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GOODS_INFO::subsystemid() const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO.subSystemId)
  return subsystemid_.GetNoArena();
}
inline void GOODS_INFO::set_subsystemid(const ::std::string& value) {
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GOODS_INFO.subSystemId)
}
#if LANG_CXX11
inline void GOODS_INFO::set_subsystemid(::std::string&& value) {
  
  subsystemid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GOODS_INFO.subSystemId)
}
#endif
inline void GOODS_INFO::set_subsystemid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GOODS_INFO.subSystemId)
}
inline void GOODS_INFO::set_subsystemid(const void* value, size_t size) {
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GOODS_INFO.subSystemId)
}
inline ::std::string* GOODS_INFO::mutable_subsystemid() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO.subSystemId)
  return subsystemid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GOODS_INFO::release_subsystemid() {
  // @@protoc_insertion_point(field_release:X.Res.GOODS_INFO.subSystemId)
  
  return subsystemid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GOODS_INFO::set_allocated_subsystemid(::std::string* subsystemid) {
  if (subsystemid != NULL) {
    
  } else {
    
  }
  subsystemid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), subsystemid);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GOODS_INFO.subSystemId)
}

// -------------------------------------------------------------------

// GOODS_INFO_ARRAY

// repeated .X.Res.GOODS_INFO items = 1;
inline int GOODS_INFO_ARRAY::items_size() const {
  return items_.size();
}
inline void GOODS_INFO_ARRAY::clear_items() {
  items_.Clear();
}
inline const ::X::Res::GOODS_INFO& GOODS_INFO_ARRAY::items(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GOODS_INFO_ARRAY.items)
  return items_.Get(index);
}
inline ::X::Res::GOODS_INFO* GOODS_INFO_ARRAY::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.GOODS_INFO_ARRAY.items)
  return items_.Mutable(index);
}
inline ::X::Res::GOODS_INFO* GOODS_INFO_ARRAY::add_items() {
  // @@protoc_insertion_point(field_add:X.Res.GOODS_INFO_ARRAY.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO >*
GOODS_INFO_ARRAY::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GOODS_INFO_ARRAY.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::X::Res::GOODS_INFO >&
GOODS_INFO_ARRAY::items() const {
  // @@protoc_insertion_point(field_list:X.Res.GOODS_INFO_ARRAY.items)
  return items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace Res
}  // namespace X

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GOODS_5fINFO_2eproto__INCLUDED
