// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountInfo.proto

#ifndef PROTOBUF_AccountInfo_2eproto__INCLUDED
#define PROTOBUF_AccountInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace X {
namespace Res {
class AccountInfo;
class AccountInfoDefaultTypeInternal;
extern AccountInfoDefaultTypeInternal _AccountInfo_default_instance_;
class AccountInfo_ARRAY;
class AccountInfo_ARRAYDefaultTypeInternal;
extern AccountInfo_ARRAYDefaultTypeInternal _AccountInfo_ARRAY_default_instance_;
}  // namespace Res
}  // namespace X

namespace X {
namespace Res {

namespace protobuf_AccountInfo_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_AccountInfo_2eproto

// ===================================================================

class AccountInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.AccountInfo) */ {
 public:
  AccountInfo();
  virtual ~AccountInfo();

  AccountInfo(const AccountInfo& from);

  inline AccountInfo& operator=(const AccountInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AccountInfo(AccountInfo&& from) noexcept
    : AccountInfo() {
    *this = ::std::move(from);
  }

  inline AccountInfo& operator=(AccountInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AccountInfo& default_instance();

  static inline const AccountInfo* internal_default_instance() {
    return reinterpret_cast<const AccountInfo*>(
               &_AccountInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(AccountInfo* other);
  friend void swap(AccountInfo& a, AccountInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AccountInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  AccountInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AccountInfo& from);
  void MergeFrom(const AccountInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AccountInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint32 Num = 2;
  void clear_num();
  static const int kNumFieldNumber = 2;
  ::google::protobuf::uint32 num() const;
  void set_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:X.Res.AccountInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 num_;
  mutable int _cached_size_;
  friend struct protobuf_AccountInfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AccountInfo_ARRAY : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.AccountInfo_ARRAY) */ {
 public:
  AccountInfo_ARRAY();
  virtual ~AccountInfo_ARRAY();

  AccountInfo_ARRAY(const AccountInfo_ARRAY& from);

  inline AccountInfo_ARRAY& operator=(const AccountInfo_ARRAY& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AccountInfo_ARRAY(AccountInfo_ARRAY&& from) noexcept
    : AccountInfo_ARRAY() {
    *this = ::std::move(from);
  }

  inline AccountInfo_ARRAY& operator=(AccountInfo_ARRAY&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AccountInfo_ARRAY& default_instance();

  static inline const AccountInfo_ARRAY* internal_default_instance() {
    return reinterpret_cast<const AccountInfo_ARRAY*>(
               &_AccountInfo_ARRAY_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(AccountInfo_ARRAY* other);
  friend void swap(AccountInfo_ARRAY& a, AccountInfo_ARRAY& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AccountInfo_ARRAY* New() const PROTOBUF_FINAL { return New(NULL); }

  AccountInfo_ARRAY* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AccountInfo_ARRAY& from);
  void MergeFrom(const AccountInfo_ARRAY& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AccountInfo_ARRAY* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .X.Res.AccountInfo items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::X::Res::AccountInfo& items(int index) const;
  ::X::Res::AccountInfo* mutable_items(int index);
  ::X::Res::AccountInfo* add_items();
  ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo >&
      items() const;

  // @@protoc_insertion_point(class_scope:X.Res.AccountInfo_ARRAY)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo > items_;
  mutable int _cached_size_;
  friend struct protobuf_AccountInfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AccountInfo

// bytes name = 1;
inline void AccountInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AccountInfo::name() const {
  // @@protoc_insertion_point(field_get:X.Res.AccountInfo.name)
  return name_.GetNoArena();
}
inline void AccountInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.AccountInfo.name)
}
#if LANG_CXX11
inline void AccountInfo::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.AccountInfo.name)
}
#endif
inline void AccountInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.AccountInfo.name)
}
inline void AccountInfo::set_name(const void* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.AccountInfo.name)
}
inline ::std::string* AccountInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.AccountInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AccountInfo::release_name() {
  // @@protoc_insertion_point(field_release:X.Res.AccountInfo.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AccountInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:X.Res.AccountInfo.name)
}

// uint32 Num = 2;
inline void AccountInfo::clear_num() {
  num_ = 0u;
}
inline ::google::protobuf::uint32 AccountInfo::num() const {
  // @@protoc_insertion_point(field_get:X.Res.AccountInfo.Num)
  return num_;
}
inline void AccountInfo::set_num(::google::protobuf::uint32 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:X.Res.AccountInfo.Num)
}

// -------------------------------------------------------------------

// AccountInfo_ARRAY

// repeated .X.Res.AccountInfo items = 1;
inline int AccountInfo_ARRAY::items_size() const {
  return items_.size();
}
inline void AccountInfo_ARRAY::clear_items() {
  items_.Clear();
}
inline const ::X::Res::AccountInfo& AccountInfo_ARRAY::items(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.AccountInfo_ARRAY.items)
  return items_.Get(index);
}
inline ::X::Res::AccountInfo* AccountInfo_ARRAY::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.AccountInfo_ARRAY.items)
  return items_.Mutable(index);
}
inline ::X::Res::AccountInfo* AccountInfo_ARRAY::add_items() {
  // @@protoc_insertion_point(field_add:X.Res.AccountInfo_ARRAY.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo >*
AccountInfo_ARRAY::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.AccountInfo_ARRAY.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo >&
AccountInfo_ARRAY::items() const {
  // @@protoc_insertion_point(field_list:X.Res.AccountInfo_ARRAY.items)
  return items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace Res
}  // namespace X

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AccountInfo_2eproto__INCLUDED
