// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountInfo2.proto

#ifndef PROTOBUF_AccountInfo2_2eproto__INCLUDED
#define PROTOBUF_AccountInfo2_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace X {
namespace Res {
class AccountInfo2;
class AccountInfo2DefaultTypeInternal;
extern AccountInfo2DefaultTypeInternal _AccountInfo2_default_instance_;
class AccountInfo2_ARRAY;
class AccountInfo2_ARRAYDefaultTypeInternal;
extern AccountInfo2_ARRAYDefaultTypeInternal _AccountInfo2_ARRAY_default_instance_;
}  // namespace Res
}  // namespace X

namespace X {
namespace Res {

namespace protobuf_AccountInfo2_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_AccountInfo2_2eproto

// ===================================================================

class AccountInfo2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.AccountInfo2) */ {
 public:
  AccountInfo2();
  virtual ~AccountInfo2();

  AccountInfo2(const AccountInfo2& from);

  inline AccountInfo2& operator=(const AccountInfo2& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AccountInfo2(AccountInfo2&& from) noexcept
    : AccountInfo2() {
    *this = ::std::move(from);
  }

  inline AccountInfo2& operator=(AccountInfo2&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AccountInfo2& default_instance();

  static inline const AccountInfo2* internal_default_instance() {
    return reinterpret_cast<const AccountInfo2*>(
               &_AccountInfo2_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(AccountInfo2* other);
  friend void swap(AccountInfo2& a, AccountInfo2& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AccountInfo2* New() const PROTOBUF_FINAL { return New(NULL); }

  AccountInfo2* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AccountInfo2& from);
  void MergeFrom(const AccountInfo2& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AccountInfo2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:X.Res.AccountInfo2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_AccountInfo2_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AccountInfo2_ARRAY : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.AccountInfo2_ARRAY) */ {
 public:
  AccountInfo2_ARRAY();
  virtual ~AccountInfo2_ARRAY();

  AccountInfo2_ARRAY(const AccountInfo2_ARRAY& from);

  inline AccountInfo2_ARRAY& operator=(const AccountInfo2_ARRAY& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AccountInfo2_ARRAY(AccountInfo2_ARRAY&& from) noexcept
    : AccountInfo2_ARRAY() {
    *this = ::std::move(from);
  }

  inline AccountInfo2_ARRAY& operator=(AccountInfo2_ARRAY&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AccountInfo2_ARRAY& default_instance();

  static inline const AccountInfo2_ARRAY* internal_default_instance() {
    return reinterpret_cast<const AccountInfo2_ARRAY*>(
               &_AccountInfo2_ARRAY_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(AccountInfo2_ARRAY* other);
  friend void swap(AccountInfo2_ARRAY& a, AccountInfo2_ARRAY& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AccountInfo2_ARRAY* New() const PROTOBUF_FINAL { return New(NULL); }

  AccountInfo2_ARRAY* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AccountInfo2_ARRAY& from);
  void MergeFrom(const AccountInfo2_ARRAY& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AccountInfo2_ARRAY* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .X.Res.AccountInfo2 items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::X::Res::AccountInfo2& items(int index) const;
  ::X::Res::AccountInfo2* mutable_items(int index);
  ::X::Res::AccountInfo2* add_items();
  ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo2 >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo2 >&
      items() const;

  // @@protoc_insertion_point(class_scope:X.Res.AccountInfo2_ARRAY)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo2 > items_;
  mutable int _cached_size_;
  friend struct protobuf_AccountInfo2_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AccountInfo2

// -------------------------------------------------------------------

// AccountInfo2_ARRAY

// repeated .X.Res.AccountInfo2 items = 1;
inline int AccountInfo2_ARRAY::items_size() const {
  return items_.size();
}
inline void AccountInfo2_ARRAY::clear_items() {
  items_.Clear();
}
inline const ::X::Res::AccountInfo2& AccountInfo2_ARRAY::items(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.AccountInfo2_ARRAY.items)
  return items_.Get(index);
}
inline ::X::Res::AccountInfo2* AccountInfo2_ARRAY::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.AccountInfo2_ARRAY.items)
  return items_.Mutable(index);
}
inline ::X::Res::AccountInfo2* AccountInfo2_ARRAY::add_items() {
  // @@protoc_insertion_point(field_add:X.Res.AccountInfo2_ARRAY.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo2 >*
AccountInfo2_ARRAY::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.AccountInfo2_ARRAY.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::X::Res::AccountInfo2 >&
AccountInfo2_ARRAY::items() const {
  // @@protoc_insertion_point(field_list:X.Res.AccountInfo2_ARRAY.items)
  return items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace Res
}  // namespace X

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AccountInfo2_2eproto__INCLUDED
